server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serverUrl:
      defaultZone: http://localhost:8761/eureka
      
spring:
  main:
    web-application-type: reactive
  application:
    name: APIGateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            exposedHeaders: "*"
      routes:
        - id: supplier-service
          uri: http://localhost:8087/
          predicates:
            - Path=/supplier/**
          filters:
            - RewritePath=/supplier(?<segment>/?.*), $\{segment}
            #
        - id: booking-service
          uri: http://localhost:8086/
          predicates:
            - Path=/booking/**
          filters:
            - RewritePath=/booking(?<segment>/?.*), $\{segment}
            #
        - id: email-service
          uri: http://localhost:8084/
          predicates:
            - Path=/email/**
          filters:
            - RewritePath=/email(?<segment>/?.*), $\{segment}
            #
        - id: payment-service
          uri: http://localhost:8088/
          predicates:
            - Path=/payment/**
          filters:
            - RewritePath=/payment(?<segment>/?.*), $\{segment}
            #
        - id: user-service
          uri: http://localhost:8082/
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/user(?<segment>/?.*), $\{segment}
            #
        - id: authentication-service
          uri: http://localhost:8085/
          predicates:
            - Path=/authentication/**
          filters:
            - RewritePath=/authentication(?<segment>/?.*), $\{segment}
            #
        - id: product-webapp
          uri: http://localhost:4200/
          predicates:
            - Path=/**
          filters:
            - RewritePath=(?<segment>/?.*), $\{segment}